name: Deploy to Cloudflare Pages

on:
  push:
    branches:
      - main

jobs:
  # Etapa 1: Instalación y construcción
  install-and-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Instalar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Instalar dependencias
        run: npm ci

      - name: Construir sitio
        run: npm run build

      - name: Guardar artefacto de construcción
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/

  # Etapa 2: Validación y pruebas
  test:
    runs-on: ubuntu-latest
    needs: install-and-build
    steps:
      - uses: actions/checkout@v4

      - name: Instalar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Instalar dependencias
        run: npm ci

      - name: Validar sintaxis
        run: npm run check

      - name: Ejecutar tests unitarios
        run: npm run test

  # Etapa 3: Publicación
  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4

      - name: Descargar artefacto de construcción
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist

      - name: Publicar en Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: "cicd-demo"
          directory: "dist"